[package]
description = "compute engine for index and factor"
edition = "2021"
license = "Apache-2.0"
name = "rapidash"
repository = "https://github.com/lipicoder/rapidash"
version = "0.1.0"

[[bin]]
bench = false
name = "rapidash"
path = "src/main.rs"
test = false

[dependencies]
ballista = {version = "0.9.0"}
datafusion = {version = "13.0.0"}
tokio = {version = "1.0.0", feature = ["rt", "macros"]}
